# Generated by Django 6.0.4 on 2026-04-18 21:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal del registro de bitácora', primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField(help_text='UUID del usuario que realizó la acción (referencia a Supabase auth.users)')),
                ('usuario_email', models.EmailField(help_text='Email del usuario al momento de la acción (para consultas rápidas)', max_length=254)),
                ('accion', models.CharField(help_text='Tipo de acción realizada: LOGIN, LOGOUT, REGISTER, CHANGE_ROLE, TOGGLE_ACTIVE, etc.', max_length=255)),
                ('detalles', models.JSONField(default=dict, help_text='Información adicional en formato JSON: IP, navegador, cambios realizados, etc.')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exacta en que se registró la acción (UTC)')),
            ],
            options={
                'verbose_name': 'Registro de Bitácora',
                'verbose_name_plural': 'Bitácora del Sistema',
                'db_table': 'bitacora',
                'ordering': ['-fecha'],
            },
        ),
    ]
